### ISSUE TITLE
Error: MZ and intensity lengths do not match

### ISSUE THREAD

**Issue by mengchen18** [weerapana-lab/ionFinder#9]
Dear @ajmaurais,

Thanks again for creating ionFinder and you have solved one issue for us already. We have run through your example code, but unfortunate, we encountered a problem when we apply the code to our own data (from MaxQuant). It would be great if you can help us with the problem. 

Here is the link to download data to reproduce the error: 
https://syncandshare.lrz.de/getlink/fiJkKpudQ7rH22k9xNWGgm/ionFinder_error_reproduce

There are four files:
- 01277_B02_P013129_S00_N10_R1.raw : thermo .raw file
- 01277_B02_P013129_S00_N10_R1.mzML : mzML file converted from thermo .raw file using msconvert
- msms.txt : outout file from MaxQuant
- msms_parsed.tsv : output of parse_maxquant

**What we did:**

Go to the folder containing file listed above, run:
```
parse_maxquant msms.txt 
```
This step runs without problem, here is the output:
```
parse_maxquant

Reading msms.txt... Done!
Iterating through modifications to make sure their composition is known...Success!
Grouping by precursorFile, sequence.
Writing msms_parsed.tsv... Done!
```
Then is the _ionFinder_ step:
```
ionFinder -i tsv --citStats msms_parsed.tsv
```
I run into a problem at this step, here is the output:
```
ionFinder v1.0.1

Reading input .tsv files...Done!

Searching ms2s for fragment ions using 1 thread(s)...
terminate called after throwing an instance of 'utils::InvalidXmlFile'
  what():  ERROR In scan: 15756
	MZ and intensity lengths do not match
Aborted (core dumped)
```

I have manually check the scan "15756" where I do see the intensity and MZ have the same length. Perhaps this is a bug here?
https://github.com/ajmaurais/peptideUtils/blob/master/src/msInterface/mzMLFile.cpp

Thanks again for your help. 
Best,
Chen

**Comment by mengchen18** [comment]
The example data has been updated.

**Comment by ajmaurais** [comment]
Hi Chen. There was indeed a bug in the `MzMLFile::getScan` function. I just merged a fix into the master branch. If you update your clone of the `ionFinder` repo and `peptideUtils` sub-repo and recompile, the file you shared should now work.

**Comment by mengchen18** [comment]
Thanks. It's run through now. 
Next step I  want to envoMatch. But when I run it, it shows lot of warning messages like below. Does it safe to ignore them?
I hope it's a quick question. But please let me know if not, I can create another issue in the envoMatch repo to reproduce the warnings. 

```
/home/chen/.local/lib/python3.8/site-packages/pyteomics/mass/mass.py:330: FutureWarning: charge and charge carrier should be specified when calling mass(). Support for charge in Composition.__init__ will be removed in a future version.
  warnings.warn('charge and charge carrier should be specified when calling mass(). '
/home/chen/.local/lib/python3.8/site-packages/pyteomics/mass/mass.py:471: UserWarning: Charge is not specified, but the Composition contains protons. Assuming m/z calculation.
  warnings.warn('Charge is not specified, but the Composition contains protons. Assuming m/z calculation.')
```

**Comment by ajmaurais** [comment]
That warning is from an newer version of pyteomics which is one of the envoMatch dependencies. I tested envoMatch with your data and you can safely ignore the error message. If you find the warnings annoying, I also just committed a fix in the envoMatch repo which should fix the warnings.

**Comment by mengchen18** [comment]
Great, thanks for quick response!
